улучшить Filmorate 11 спринт
musegi/java-filmorate pull request #3
Opened 2024-09-18 19:21 UTC by musegi

2024-09-18 21:06 UTC, musegi commented
помогите 😭

2024-09-19 18:19 UTC, NikolaiDem requested changes

2024-09-19 18:19 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +    public ErrorResponse handleNotFoundException(NotFoundException exp) {
Все ошибки еще лучше и логировать

2024-09-19 18:19 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotEmpty(message = "Название фильма должно быть указано.")
NotEmpty можно убрать, если указано NotBlank

2024-09-19 18:19 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotEmpty(message = "Email должен быть указан.")
NotEmpty можно убрать, если указано NotBlank

2024-09-19 18:19 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final InMemoryFilmStorage filmStorage;
В качестве зависимости лучше указывать интерфейсы, это добавляет гибкость к выбору реализации

2024-09-19 18:19 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private long getNextId() {
Лучше сделать в репозитории метод nextId(), который вернет свободный id. Это позволит "незаметно" для сервиса поменять алгоритм генерации id, если это понадобится.
Аналогично для UserService

2024-09-20 15:52 UTC, NikolaiDem approved these changes

2024-09-20 16:14 UTC, merged